# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2 # Thrid party action that helps with install the ssh key on the CD machine
        with:
            key: ${{ secrets.ACPA_SSH_PRIVATE_KEY }}
            known_hosts: ${{ secrets.ACPA_SSH_KNOWN_HOSTS }}
      
      - name: Install dependencies
        run: npm install

      - name: Install craco 
        run: npm install -g @craco/craco
      
      - name: Creating .env file
        run: |
          touch .env
          echo REACT_APP_BACKEND_SERVER=${{ secrets.ACPA_REACT_APP_BACKEND_SERVER }} >> .env
          echo REACT_APP_FRONTEND_SERVER=${{ secrets.ACPA_REACT_APP_FRONTEND_SERVER }} >> .env
          echo REACT_APP_STRIPE_PK=${{ secrets.ACPA_REACT_APP_STRIPE_PK }} >> .env
          echo NODE_ENV=production 
          cat .env

      - name: Check files
        run: ls

      - name: Creating React files
        run: npm run build
      
      - name: Removing env file
        run: rm -rf .env
      
      - name: Check files
        run: ls

      - name: Upload to Ubuntu
        run: rsync -avzr . ubuntu@174.138.20.136:~/acpa-cms-react 
