# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build # Build react project running command
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2 # Thrid party action that helps with install the ssh key on the CD machine
        with:
            key: ${{ secrets.ACPA_SSH_PRIVATE_KEY }}
            known_hosts: ${{ secrets.ACPA_SSH_KNOWN_HOSTS }}
    
      - name: Upload to Ubuntu
        run: rsync -avzr . ubuntu@174.138.20.136:~/acpa-cms-react 
